---
- name: Install monitoring tools
  dnf:
    name:
      - audit
      - setools
    state: present

- name: Create audit rule for PHP exploits
  lineinfile:
    path: /etc/audit/rules.d/web.rules
    line: "-w /var/www/vuln_app/index.php -p wa -k web_exploit"
    create: yes

- name: Restart auditd
  service:
    name: auditd
    state: restarted

- name: Create test exploit script
  copy:
    dest: /home/vagrant/test_exploit.sh
    content: |
      #!/bin/bash
      echo "Testing PHP exploit:"
      curl -s "http://localhost/?cmd=id"
      echo -e "\n\nTesting file write attempt:"
      curl -s "http://localhost/?cmd=echo%20'hacked'%20%3E%20/etc/hacked"
    mode: 0755

- name: Create exploitation guide
  copy:
    dest: /home/vagrant/README.txt
    content: |
      Lab Instructions:
      1. Access the vulnerable web application: http://localhost/?cmd=id
      2. Try to explore the system: ?cmd=ls+-la+/usr/local/bin
      3. Find the SUID binary: ?cmd=find+/+-perm+-4000+2>/dev/null
      4. Try to execute the SUID binary
      5. Check /var/log/audit/audit.log and SELinux alerts

      Generate Security Report:
      - After performing exploitation attempts, run: ./generate_report.sh
      - Reports will be saved in your home directory as security_report_<timestamp>.txt

      The report includes:
      - SELinux denial events timeline
      - Privilege escalation attempts
      - Web application exploitation attempts
      - Detailed SELinux alerts
      - File access violations with explanations

      Challenge Details:
      - Initial access is through the web application as www-data user
      - Look for SUID binaries that might help escalate privileges
      - Monitor /var/log/audit/audit.log for SELinux alerts
      - The flag is stored in /root/flag.txt
    mode: 0644

- name: Create reporting script
  copy:
    dest: /home/vagrant/generate_report.sh
    content: |
      #!/bin/bash
      echo "Generating Security Analysis Report..."
      sudo /usr/local/bin/analyze_security_events.sh > ~/security_report_$(date +%Y%m%d_%H%M%S).txt
      echo "Report generated!"
    mode: 0755