# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos9s"
  config.vm.box_version = "4.2.16"
  
  config.vm.network "forwarded_port", guest: 80, host: 8080
  
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = true  # Optional: Enable VM GUI
    vmware.memory = 2048
    vmware.cpus = 2
    vmware.enable_vmrun_ip_lookup = false  # Fix IP detection if needed
  end

  # Enable SELinux in enforcing mode (default for CentOS)
  # If SELinux is disabled in the box, add a shell provisioner:
  config.vm.provision "shell", inline: <<-SHELL
    sudo sed -i 's/SELINUX=.*/SELINUX=enforcing/' /etc/selinux/config
    sudo setenforce 1
  SHELL

  # Ansible provisioning
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.become = true
    ansible.compatibility_mode = "2.0"
    ansible.verbose = "v"
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python3"
    }
  end
end
