- name: Configure SELinux Lab Environment
  hosts: default
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Show detected IP
      debug:
        msg: "VM IP: {{ ansible_host }}"
        
    - name: Install SELinux utilities
      dnf:
        name:
          - policycoreutils-python-utils
          - selinux-policy-targeted
          - setroubleshoot
          - audit
        state: present

  roles:
    - selinux_setup
    - selinux_nginx
    - restricted_user
    - log_analysis
    - exploit_demo
    # - squirrelmail

  post_tasks:
    - name: Verify service contexts
      shell: "ps -eZ | grep -E 'nginx|httpd' || true"
      register: service_contexts
      changed_when: false

    - name: Display security contexts
      debug:
        var: service_contexts.stdout_lines

    - name: Generate initial security report
      command: sealert -a /var/log/audit/audit.log
      register: security_report
      changed_when: false

    - name: Show security alerts
      debug:
        var: security_report.stdout_lines

    - name: Schedule log monitoring
      cron:
        name: "Security alert checks"
        minute: "*/5"
        job: "/usr/local/bin/check_alerts > /var/log/security_audit.log 2>&1"